### ISSUE TITLE
Sub Directory 

### ISSUE THREAD

**Issue by Apex-94** [iotarepeat/PySync#1] opened 2019-02-26 15:23 UTC
.Make a folder in Desktop example Test
2.Make another folder in Test example Test2
3.Make a file in Test folder HelloWorld.txt
4.Run server file, Run client file .
5.Client File in Test2

**Comment by iotarepeat** [comment] 2019-02-26 15:26
OS:
Expected Behaviour: 
Please attach screenshots if possible

**Comment by Apex-94** [comment] 2019-02-26 15:26
> Please attach screenshots if possible

Yes

**Comment by iotarepeat** [comment] 2019-02-26 15:34
This is nested directory structure. It will always cause an infinite loop since client is inside server

Closing, because this situation will not occur during practical application.

**Closed as completed by iotarepeat** 2019-02-26 15:34 UTC
